### ISSUE TITLE
ExecuteRestApiにてボディのエンコードが指定可能とする

### ISSUE THREAD

**Issue by takashno** [epion-tropic-test-tool/epion-t3#26]
#### Feature Kind（機能種別）
Choice Feature Kind（機能の種別を選んでください）
- Command（単純な処理機能）

#### Feature Description （機能詳細）
UTF-8固定でと言いたいところだが、要望があるため機能追加を行う。
デフォルト値はUTF-8とする。
ContentTypeから導き出してもいいが、charsetを指定しない場合もあるので別で実装する。

**Comment by takashno** [comment]
一旦リクエストボディのみを対応する。
レスポンスにマルチバイト文字列が含まれる場合に、レポートが文字化ける可能性があるような気がする。その場合は、Acceptヘッダの値？それともコマンドで個別指定でどうにかするか・・・

**Comment by oganao** [comment]
Shift_JISを指定したいpostに対して、bodyEncodingにShift_JISを設定しても文字化けが発生しました。
また、bodyEncodingにUTF-8、content-typeのcharsetにShift_JIS、又はWindows-31Jを指定したところ文字化けが発生せず正常に完了しました。

**Comment by takashno** [comment]
すみません、糞バグでした。
ちなみに、レポートが文字化けるかもしれない・・・

**Comment by takashno** [comment]
確認済み。
