### ISSUE TITLE
DATEやTIMESTAMPといったデータ型(例 : 2020-09-23 0:01:00)の時間部分が、Excel投入時に省略されてしまう

### ISSUE THREAD

**Issue by kobayate** [epion-tropic-test-tool/epion-t3#42]
ソースを見させていただいたのですが、XlsxDataSetWriter.javaでlong型で受け取ってしまうDATE型データを、再度日付データで変換していると思います。
その際に、(取得してきたlong型データ) ÷ 60000 == 0ならシンプル表記(例 :2020-09-25)
それ以外なら、そのままの表記(2020-09-25 12:34:56)
という処理を行っていると思いますが、2020-09-25 12:00:00をlong型で表した値も60000で割り切れてしまっていて、時間情報が省略されてしまっているようです。
一度ご確認いただけないでしょうか。

追記：
DATE型は yyyy-mm-dd hh:mm:ss
TIMESTAMP型は yyyy-mm-dd hh:mm:ss.(小数点以下3桁)
の形で表示したいです。

**Comment by takashno** [comment]
DBUnitのXlsDataSetWriterを拡張しており、元クラスがjava.util.Dateで保持しています。
この時点でDBの元の型を意識した処理分岐は無理だと思います。
テストツールとしては、丸められる事自体が悪であると考え、
一律 `yyyy-MM-dd HH:mm:ss.SSS` に寄せるという考え方ならば対応が可能ですしテスト時にも困ることはないと考えますが、いかがでしょうか？

**Comment by kobayate** [comment]
ありがとうございます。
一度こちらの方でも相談し、再度ご連絡致します。

**Comment by kobayate** [comment]
@takashno の提案通り一律、"yyyy-mm-dd hh:mm:ss.SSS"の形式で試験を行う方向で問題ないですね。
可能であれば、ご対応よろしくお願い致します。

**Comment by takashno** [comment]
こちら対応しました。
確認お願いします。
Versionは0.0.2で変わらずです。

**Comment by kobayate** [comment]
"yyyy-mm-dd hh:mm:ss.SSS"の形式で試験ができることを確認しました。
ご対応ありがとうございました。

**Comment by takashno** [comment]
対応完了のためCloseする
